# Generated by Django 5.0.1 on 2024-01-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='name',
            field=models.CharField(),
        ),
    ]
